config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resource :search, only: [:new, :show]

  resources :routes
  resources :tickets
  resources :trains do
    resources :carriages, except: :index, shallow: true
  end
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  %i(business_carriages coupe_carriages economy_carriages seating_carriages).each do |c|
    resources c, controller: :carriages
  end
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route
  belongs_to :current_station, class_name: "RailwayStation", foreign_key: :current_station_id
  has_many :tickets
  has_many :carriages

  validates :number, presence: true

  def count_places(carriage_type, places_type)
    total_places = 0
    carriages.where(type: carriage_type).each do |c|
      places = "#{places_type}_places".to_sym
      total_places += c.send(places)
    end
    total_places
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
    if @train.reverse_ordered
      @carriages = @train.carriages.reverse_ordered
    else
      @carriages = @train.carriages.ordered
    end
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_url, notice: 'Train was successfully destroyed.'
  end

  private
    def set_train
      @train = Train.find(params[:id])
    end

    def train_params
      params.require(:train).permit(:number, :route_id, :current_station_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_carriages.html.slim
h4
  b Carriages: 
- if @train.carriages.present?
  table.table.table-bordered
    - @train.carriages.each do |c|
      tr
        td
          = link_to c do
            p.pull-left #{ c.model_name.human } ##{ c.number }
          = link_to "Remove", carriage_path(c), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger pull-right"
- else   
  p No carriages yet.
= link_to "Add carriage", new_train_carriage_path(@train)

app/views/trains/_form.html.haml
= form_for @train do |f|
  - if @train.errors.any?
    #error_explanation
      %h2= "#{pluralize(@train.errors.count, "error")} prohibited this train from being saved:"
      %ul
        - @train.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

app/views/trains/_form.html.slim
= form_for @train do |f|
  = render "shared/errors", resource: @train

  .form-group
    = f.label :number
    = f.text_field :number, class: "form-control"
  .form-group
    = f.label :route
    = f.collection_select :route_id, Route.all, :id, :title, {}, { class: "form-control" }
  .form-group
    = f.label :current_station
    = f.collection_select :current_station_id, RailwayStation.all, :id, :title, {}, { class: "form-control" }
  .actions
    = f.submit @train.new_record? ? 'Create train' : 'Update train' , class: "btn btn-primary"

app/views/trains/_train.html.slim
.list-entity
  p= link_to train.number, train
  .btn-group.pull-right
    = link_to "Edit", edit_train_path(train), class: "btn btn-default btn-sm"
    = link_to "Remove", train_path(train), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"
    
  .clearfix

app/views/trains/edit.html.haml
%h1 Editing train

= render 'form'

= link_to 'Show', @train
\|
= link_to 'Back', trains_path

app/views/trains/edit.html.slim
.container

  h1.text-center Edit train
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

    .col-md-8.col-md-offset-2
      .btn-group
        = link_to 'Show', @train, class: "btn btn-primary"
        = link_to 'Back', trains_path, class: "btn btn-default"

app/views/trains/index.html.slim
.container

  h1.text-center Trains list
  br
  .row
    .col-md-8.col-md-offset-2
      .well
        = render @trains
    
      = link_to "Add train", new_train_path, class: "btn btn-default"

app/views/trains/new.html.haml
%h1 New train

= render 'form'

= link_to 'Back', trains_path

app/views/trains/new.html.slim
.container

  h1.text-center New train
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

      = link_to 'Back', trains_path, class: "btn btn-default"

app/views/trains/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @train.number

= link_to 'Edit', edit_train_path(@train)
\|
= link_to 'Back', trains_path

app/views/trains/show.html.slim
.container

  p#notice= notice

  h1.text-center Train ##{@train.number}
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render "trains/carriages"
        hr
        
        h4
          b Route: 
          - if @train.route.present?
            = @train.route.title
          - else
            | Not specified
        hr 
        
        h4
          b Current station: 
          - if @train.current_station.present?
            = @train.current_station.title
          - else
            | Not specified
            
  .row
    .col-md-8.col-md-offset-2
      .btn-group
        = link_to "Edit", edit_train_path(@train), class: "btn btn-primary"
        = link_to 'Back', trains_path, class: "btn btn-default"