config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resource :search, only: [:new, :show]

  resources :routes
  resources :tickets
  resources :trains do
    resources :carriages, except: :index, shallow: true
  end
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  %i(business_carriages coupe_carriages economy_carriages seating_carriages).each do |c|
    resources c, controller: :carriages
  end
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  has_many :trains, foreign_key: :current_station_id

  validates :title, presence: true

  scope :ordered, -> { order("railway_stations_routes.position") }

  def update_position(route, position)
    station_route = station_route(route)
    station_route.update(position: position) if station_route
  end

  def update_arrival(route, arrival)
    station_route = station_route(route)
    station_route.update(arrival: arrival) if station_route
  end

  def update_departure(route, departure)
    station_route = station_route(route)
    station_route.update(departure: departure) if station_route
  end

  def current_position(route)
    station_route(route).try(:position)
  end

  def current_arrival(route)
    station_route(route).arrival.strftime("%H:%M") if station_route(route).try(:arrival)
  end

  def current_departure(route)
    station_route(route).departure.strftime("%H:%M") if station_route(route).try(:departure)
  end

  private

  def station_route(route)
    station_route ||= railway_stations_routes.where(route: route).first
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy, :update_position, :update_arrival, :update_departure]
  before_action :set_route, only: [:update_position, :update_arrival, :update_departure]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

  def edit
  end

  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station, notice: 'Railway station was successfully created.'
    else
      render :new
    end
  end

  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station, notice: 'Railway station was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @railway_station.destroy
    redirect_to railway_stations_url, notice: 'Railway station was successfully destroyed.'
  end

  def update_position
    @railway_station.update_position(@route, params[:position])
    redirect_to @route
  end

  def update_arrival
    @railway_station.update_arrival(@route, params[:arrival])
    redirect_to @route
  end

  def update_departure
    @railway_station.update_departure(@route, params[:departure])
    redirect_to @route
  end

  private
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    def set_route
      @route = Route.find(params[:route_id])
    end

    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/views/railway_stations/_form.html.haml
= form_for @railway_station do |f|
  - if @railway_station.errors.any?
    #error_explanation
      %h2= "#{pluralize(@railway_station.errors.count, "error")} prohibited this railway_station from being saved:"
      %ul
        - @railway_station.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/railway_stations/_form.html.slim
= form_for @railway_station do |f|

  = render "shared/errors", resource: @railway_station
          
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .actions
    = f.submit @railway_station.new_record? ? 'Create station' : 'Update station' , class: "btn btn-primary"

app/views/railway_stations/_railway_station.html.slim
.list-entity
  p= link_to railway_station.title, railway_station
  .btn-group.pull-right
    = link_to "Edit", edit_railway_station_path(railway_station), class: "btn btn-default btn-sm"
    = link_to "Remove", railway_station_path(railway_station), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"
    
  .clearfix

app/views/railway_stations/edit.html.haml
%h1 Editing railway_station

= render 'form'

= link_to 'Show', @railway_station
\|
= link_to 'Back', railway_stations_path

app/views/railway_stations/edit.html.slim
.container

  h1.text-center Edit railway station
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

    .col-md-8.col-md-offset-2
      .btn-group
        = link_to 'Show', @railway_station, class: "btn btn-primary"
        = link_to 'Back', railway_stations_path, class: "btn btn-default"

app/views/railway_stations/index.html.slim
.container

  h1.text-center Railway Stations list
  br
  .row
    .col-md-8.col-md-offset-2
      .well
        = render @railway_stations
    
      = link_to "Add railway station", new_railway_station_path, class: "btn btn-default"

app/views/railway_stations/new.html.haml
%h1 New railway_station

= render 'form'

= link_to 'Back', railway_stations_path

app/views/railway_stations/new.html.slim
.container

  h1.text-center New railway station
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

      = link_to 'Back', railway_stations_path, class: "btn btn-default"

app/views/railway_stations/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @railway_station.title

= link_to 'Edit', edit_railway_station_path(@railway_station)
\|
= link_to 'Back', railway_stations_path

app/views/railway_stations/show.html.slim
.container

  p#notice= notice

  h1.text-center= @railway_station.title
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        h3
          b Trains: 
        - if @railway_station.trains.any?
          = render @railway_station.trains
        - else
          p There are currently no trains.
  .row
    .col-md-8.col-md-offset-2
      .btn-group
        = link_to 'Edit', edit_railway_station_path(@railway_station), class: "btn btn-primary"
        = link_to 'Back', railway_stations_path, class: "btn btn-default"