config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resource :search, only: [:new, :show]

  resources :routes
  resources :tickets
  resources :trains do
    resources :carriages, except: :index, shallow: true
  end
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  %i(business_carriages coupe_carriages economy_carriages seating_carriages).each do |c|
    resources c, controller: :carriages
  end
end

app/models/search.rb
class Search

  def self.get_trains(departure, arrival)
    if departure != arrival
      routes = Route.joins(:railway_stations).where(railway_stations: { id: departure }) & Route.joins(:railway_stations).where(railway_stations: { id: arrival })
      Train.where(route: routes)
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :get_stations

  def new
    @departure = params[:search][:departure]
    @arrival = params[:search][:arrival]
    @trains = Search.get_trains(@departure, @arrival)
    render 'show'
  end

  def show

  end

  private

  def get_stations
    @stations = RailwayStation.all
  end
end

app/views/searches/show.html.slim
.container

  p#notice= notice

  h1.text-center Search
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = form_tag(new_search_path, method: "get")
          .form-inline.text-center
            .form-group
              = collection_select :search, :departure, @stations, :id, :title, {selected: @departure}, { class: "form-control" }
              | &nbsp; — &nbsp;
              = collection_select :search, :arrival, @stations, :id, :title, {selected: @arrival}, { class: "form-control" }
              | &nbsp;&nbsp;
              = button_tag type: "submit", class: "btn btn-primary" do
                = fa_icon "search"
        
        - if @trains
          br
          - if @trains.present?
            table.table.table-bordered
              tr
                td Train number
                td Departure time
                td Arrival time
                td
              - @trains.each do |t|
                tr
                  td= t.number
                  td= get_station_time(t, @departure, "departure")
                  td= get_station_time(t, @arrival, "arrival")
                  td.text-center= link_to "Buy", new_ticket_path(ticket: { train_id: t.id, departure_id: @departure, arrival_id: @arrival }), class: "btn btn-primary"
              br
          - else
            h4.text-center No trains matched your search.