config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  resource :search, only: [:new, :show]

  resources :routes
  resources :tickets
  resources :trains do
    resources :carriages, except: :index, shallow: true
  end
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  %i(business_carriages coupe_carriages economy_carriages seating_carriages).each do |c|
    resources c, controller: :carriages
  end
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :title, presence: true

  before_validation :set_route_name

  private

  def set_route_name
    self.title = "#{railway_stations.first.title} — #{railway_stations.last.title}"
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route, notice: "Route was created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route, notice: "Route was updated."
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: "Route was destroyed."
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end
end

app/views/routes/_form.html.haml
= form_for @route do |f|
  - if @route.errors.any?
    #error_explanation
      %h2= "#{pluralize(@route.errors.count, "error")} prohibited this route from being saved:"
      %ul
        - @route.errors.full_messages.each do |msg|
          %li= msg
          
  = f.label :title
  = f.text_field :title
  %br/
  %br/
  = f.submit
  
%br/
%br/

app/views/routes/_form.html.slim
= form_for @route do |f|

  = render "shared/errors", resource: @route

  .form-group
    = f.label :railway_stations
    = f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { class: "form-control", multiple: true }
  .actions
    = f.submit @route.new_record? ? 'Create route' : 'Update route' , class: "btn btn-primary"

app/views/routes/_route.html.slim
.list-entity
  p= link_to route.title, route
  .btn-group.pull-right
    = link_to "Edit", edit_route_path(route), class: "btn btn-default btn-sm"
    = link_to "Remove", route_path(route), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"
    
  .clearfix

app/views/routes/edit.html.slim
.container

  h1.text-center Edit route
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

    .col-md-8.col-md-offset-2
      .btn-group
        = link_to 'Show', @route, class: "btn btn-primary"
        = link_to 'Back', routes_path, class: "btn btn-default"

app/views/routes/index.html.haml
%h1 Routes list

%ul
  - @routes.each do |route|
    %li
      = link_to route.title, route
      &nbsp;|&nbsp;
      = link_to "Edit", edit_route_path(route)
      = link_to "Remove", route_path(route), method: :delete, data: { confirm: "Are you sure?" }
    
%p= link_to "Add route", new_route_path

app/views/routes/index.html.slim
.container

  h1.text-center Routes list
  br
  .row
    .col-md-8.col-md-offset-2
      .well
        = render @routes
    
      = link_to "Add route", new_route_path, class: "btn btn-default"

app/views/routes/new.html.slim
.container

  h1.text-center New route
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        = render 'form'

      = link_to 'Back', routes_path, class: "btn btn-default"

app/views/routes/show.html.slim
.container

  p#notice= notice

  h1.text-center= @route.title
  br
  
  .row
    .col-md-8.col-md-offset-2
      .well
        h3
          b Stations:
        - if @route.railway_stations.any?
          table.table.table-bordered
            - @route.railway_stations.ordered.each do |rs|
              tr
                td
                  = rs.title
                td
                  = form_tag update_position_railway_station_path(rs), method: :patch do
                    .input-group
                      = number_field_tag :position, rs.current_position(@route.id), class: "form-control"
                      = hidden_field_tag :route_id, @route.id
                      span.input-group-btn
                        = button_tag type: "submit", class: "btn btn-primary" do
                          = fa_icon "sort"
                td
                  = form_tag update_arrival_railway_station_path(rs), method: :patch
                    .input-group
                      = time_field_tag :arrival, rs.current_arrival(@route.id), class: "form-control"
                      = hidden_field_tag :route_id, @route.id
                      span.input-group-btn
                        = button_tag type: "submit", class: "btn btn-primary" do
                          = fa_icon "download"
                td
                  = form_tag update_departure_railway_station_path(rs), method: :patch
                    .input-group
                      = time_field_tag :departure, rs.current_departure(@route.id), class: "form-control"
                      = hidden_field_tag :route_id, @route.id
                      span.input-group-btn
                        = button_tag type: "submit", class: "btn btn-primary" do
                          = fa_icon "upload"
        - else
          p Not defined yet.
        h3
          b Trains: 
        - if @route.trains.any?
          = render @route.trains
        - else
          p There are currently no trains.
  .row
    .col-md-8.col-md-offset-2
      .btn-group
        = link_to "Edit", edit_route_path(@route), class: "btn btn-primary"
        = link_to 'Back', routes_path, class: "btn btn-default"